# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

normalize:
  _target_: emg2qwerty.transforms.NormalizeEMG

gaussian_noise:
  _target_: emg2qwerty.transforms.GaussianNoise
  std: 0.01  # adjust noise level as desired

channel_dropout:
  _target_: emg2qwerty.transforms.RandomChannelDropout
  drop_prob: 0.15

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4

transforms:
  train:
    - ${to_tensor}
    # - ${normalize}
    # - ${gaussian_noise}
    - ${channel_dropout}   # <-- new augmentation
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}
